language: java
jdk:
- oraclejdk8
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_ORIGIN_URL=`git config --get remote.origin.url`
  - export GIT_LAST_MESSAGE=`git log -1 --oneline --pretty=%B`
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GITHUB_KEY:@github.com" > .git/credentials
  - ./gradlew updateForgeJson
  - export GIT_TAG=TooltipFilter-$TRAVIS_BRANCH-v0.1.0.${TRAVIS_BUILD_NUMBER}
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q --all --follow-tags  > /dev/null 2>&1
  - if [[ "$GIT_LAST_MESSAGE" =~ ^\[recommended\] ]]; 
    then export GHTHUB_DEPLOY_PRERELEASE=false;
    else export GHTHUB_DEPLOY_PRERELEASE=true;
    fi
deploy:
  provider: releases
  api_key: ${GITHUB_KEY}
  file:
  - build/libs/TooltipFilter-1.11.2-0.1.0.${TRAVIS_BUILD_NUMBER}.jar
  on:
    tags: false
    all_branches: true
  skip_cleanup: true
  prerelease: ${GHTHUB_DEPLOY_PRERELEASE}
branches:
  except:
  - "/^TooltipFilter.*-v[0-9]/"
  - "/^update/"
before_install:
 - chmod +x gradlew
install: ./gradlew setupCIWorkspace
script: ./gradlew build
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/