package org.librazy.tooltipfilter;

public enum FilterMode {
    REMOVE,
    REMOVE_ALL_BUT_FIRST_MATCH,
    REMOVE_ALL_BUT_LAST_MATCH,
    REMOVE_FIRST_MATCH,
    REMOVE_LAST_MATCH,
    REMOVE_ALL_BUT_FIRST_EXACT,
    REMOVE_ALL_BUT_LAST_EXACT,
    REMOVE_FIRST_EXACT,
    REMOVE_LAST_EXACT,
    REPLACE,
    REPLACE_ALL_BUT_FIRST_MATCH,
    REPLACE_ALL_BUT_LAST_MATCH,
    REPLACE_FIRST_MATCH,
    REPLACE_LAST_MATCH,
    REPLACE_ALL_BUT_FIRST_EXACT,
    REPLACE_ALL_BUT_LAST_EXACT,
    REPLACE_FIRST_EXACT,
    REPLACE_LAST_EXACT,
    COMBINE_NEAR_MATCH,
    COMBINE_NEAR_EXACT,
}
